on: [pull_request]

env:
  CARGO_TERM_COLOR: always

name: Lint and Test

jobs:

  prover-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      
      - name: Lint
        run: |
          cd prover-node
          cargo fmt --all -- --check
          cargo clippy --no-deps -- -D warnings

      - name: Test
        run: |
          cd prover-node
          cargo test